<Project><PropertyGroup><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><LangVersion>latest</LangVersion><NuGetAudit>false</NuGetAudit><Version>26.09.0</Version><AssemblyVersion>26.9.0.0</AssemblyVersion><FileVersion>26.9.0.0</FileVersion><InformationalVersion>26.09.0</InformationalVersion></PropertyGroup></Project>
