namespace XamlForge.Core;
public static class PowerShellExporter
{
    public static string Export(DesignDocument document)
    {
        var b=new System.Text.StringBuilder();
        b.AppendLine("# Generated by XamlForge. Run with powershell.exe -STA -File or pwsh -STA -File.");
        b.AppendLine("[CmdletBinding()]\nparam([switch]$NoShow)\nSet-StrictMode -Version Latest\n$ErrorActionPreference = 'Stop'");
        b.AppendLine("if ([Threading.Thread]::CurrentThread.ApartmentState -ne 'STA') { throw 'WPF requires STA. Restart PowerShell with -STA.' }");
        b.AppendLine("Add-Type -AssemblyName PresentationFramework, PresentationCore, WindowsBase\nfunction New-Window {");
        foreach(var assembly in document.Assemblies)b.AppendLine("  Add-Type -Path '"+assembly.Replace("'","''")+"'");
        b.AppendLine("  #region XAML definition");
        if(document.Xaml.Split('\n').Any(l=>l.TrimEnd('\r').StartsWith("'@")))
            b.AppendLine("  $xamlDefinition = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('"+Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(document.Xaml))+"'))");
        else b.AppendLine("  $xamlDefinition = @'\n"+document.Xaml+"\n'@");
        b.AppendLine("  #endregion\n  $reader = [Xml.XmlReader]::Create([IO.StringReader]::new($xamlDefinition))\n  try { $window = [Windows.Markup.XamlReader]::Load($reader) } finally { $reader.Dispose() }\n  $controls = @{}");
        foreach(var e in document.Elements){var name=DesignDocument.NameOf(e);if(name.Length==0)continue;b.AppendLine("  $"+name+" = "+(e==document.Xml.Root?"$window":"$window.FindName('"+name+"')"));b.AppendLine("  $controls['"+name+"'] = $"+name);}
        b.AppendLine("  #region PowerShell event handlers");
        foreach(var h in document.Events){b.AppendLine("  $"+h.ControlName+".Add_"+h.EventName+"({\n    param($sender, $eventArgs)\n"+h.Code+"\n  }.GetNewClosure())");}
        b.AppendLine("  #endregion\n  $window | Add-Member -NotePropertyName XamlForgeControls -NotePropertyValue $controls\n  return $window\n}\n$window = New-Window\nif ($NoShow) { $window } else { [void]$window.ShowDialog() }");
        return b.ToString();
    }
}
